service: algoworks

frameworkVersion: '1'

custom:
  settings:
    POSTS_TABLE: posts
    USERS_TABLE: users

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  environment: ${self:custom.settings}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - ses:*
     Resource: '*'

functions:
  registerUser:
    handler: handler.registerUser
    events:
    - http:
        path: /user/register
        method: post
  loginUser:
    handler: handler.loginUser
    events:
    - http:
        path: /user/login
        method: post
  listUsers:
    handler: handler.listUsers
    events:
    - http:
        path: /user/list
        method: get
  getUser:
    handler: handler.getUser
    events:
    - http:
        path: /user/{email}
        method: get
  updateUser:
    handler: handler.updateUser
    events:
    - http:
        path: /user/{email}
        method: put
  deleteUser:
    handler: handler.deleteUser
    events:
    - http:
        path: /user/{email}
        method: delete
  createPost:
    handler: handler.createPost
    events:
    - http:
        path: /user/post
        method: post
  getAllPosts:
    handler: handler.getAllPosts
    events:
    - http:
        path: /user/post/list
        method: get
  getPost:
    handler: handler.getPost
    events:
    - http:
        path: /user/post/{id}
        method: get
  updatePost:
    handler: handler.updatePost
    events:
    - http:
        path: /user/post/{id}
        method: put
  deletePost:
    handler: handler.deletePost
    events:
    - http:
        path: /user/post/{id}
        method: delete

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.USERS_TABLE}
 


         
    

